package dadkvs.server;

import java.util.ArrayList;
import java.util.Iterator;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsMain;
import dadkvs.DadkvsPaxos;
import dadkvs.DadkvsPaxosServiceGrpc;

import dadkvs.util.GenericResponseCollector;
import dadkvs.util.CollectorStreamObserver;

import io.grpc.stub.StreamObserver;

public class DadkvsPaxosServiceImpl extends DadkvsPaxosServiceGrpc.DadkvsPaxosServiceImplBase {

    DadkvsServerState server_state;

    public DadkvsPaxosServiceImpl(DadkvsServerState state) {
        this.server_state = state;
    }

    @Override
    public void phaseone(DadkvsPaxos.PhaseOneRequest request,
            StreamObserver<DadkvsPaxos.PhaseOneReply> responseObserver) {
        // for debug purposes
        System.out.println("Receive phase1 request: " + request);

        DadkvsPaxos.PhaseOneReply response;

        int timestamp = request.getPhase1Timestamp();
        int config = request.getPhase1Config();
        int index = request.getPhase1Index();

        if (timestamp > this.server_state.rnd.get()
                && this.server_state.currentIndex.get() == index) {
            // Setting up the config to be used for this Paxos instance
            VersionedValue old_config = server_state.store.read(0);
            VersionedValue new_config = new VersionedValue(config, old_config.getVersion() + 1);
            server_state.store.write(0, new_config);

            this.server_state.rnd.set(timestamp);
            response = DadkvsPaxos.PhaseOneReply.newBuilder().setPhase1Config(config)
                    .setPhase1Index(index).setPhase1Timestamp(this.server_state.vrnd.get())
                    .setPhase1Accepted(true).setPhase1Value(this.server_state.vval.get()).build();

        } else {
            response = DadkvsPaxos.PhaseOneReply.newBuilder().setPhase1Config(config)
                    .setPhase1Index(index).setPhase1Timestamp(this.server_state.rnd.get())
                    .setPhase1Accepted(false).build();
        }
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void phasetwo(DadkvsPaxos.PhaseTwoRequest request,
            StreamObserver<DadkvsPaxos.PhaseTwoReply> responseObserver) {
        // for debug purposes
        System.out.println("Receive phase two request: " + request);

        DadkvsPaxos.PhaseTwoReply response;

        int timestamp = request.getPhase2Timestamp();
        int config = request.getPhase2Config();
        int index = request.getPhase2Index();

        if (timestamp > this.server_state.rnd.get()
                && this.server_state.currentIndex.get() == index) {
            this.server_state.rnd.set(timestamp);
            this.server_state.vrnd.set(timestamp);
            this.server_state.vval.set(request.getPhase2Value());
            response = DadkvsPaxos.PhaseTwoReply.newBuilder().setPhase2Config(config)
                    .setPhase2Index(index).setPhase2Accepted(true).build();

            DadkvsPaxos.LearnRequest.Builder learn_request = DadkvsPaxos.LearnRequest.newBuilder();
            learn_request.setLearnconfig(config).setLearnindex(index)
                    .setLearnvalue(this.server_state.vval.get())
                    .setLearntimestamp(this.server_state.vrnd.get());

            ArrayList<DadkvsPaxos.LearnReply> learn_responses =
                    new ArrayList<DadkvsPaxos.LearnReply>();

            GenericResponseCollector<DadkvsPaxos.LearnReply> learn_collector =
                    new GenericResponseCollector<DadkvsPaxos.LearnReply>(learn_responses,
                            this.server_state.n_servers);

            for (int j = 0; j < this.server_state.n_servers; j++) {
                if (j == this.server_state.my_id)
                    continue;

                CollectorStreamObserver<DadkvsPaxos.LearnReply> execute_observer =
                        new CollectorStreamObserver<DadkvsPaxos.LearnReply>(learn_collector);
                this.server_state.async_stubs[j].learn(learn_request.build(), execute_observer);
            }
            learn_collector.waitForTarget(this.server_state.responses_needed);
        } else {
            response = DadkvsPaxos.PhaseTwoReply.newBuilder().setPhase2Config(config)
                    .setPhase2Index(index).setPhase2Accepted(false).build();
        }
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void learn(DadkvsPaxos.LearnRequest request,
            StreamObserver<DadkvsPaxos.LearnReply> responseObserver) {
        // for debug purposes
        System.out.println("Received learn request: " + request);

        DadkvsPaxos.LearnReply response;

        int value = request.getLearnvalue();
        int config = request.getLearnconfig();
        int index = request.getLearnindex();

        PendingRequest newRequest = new PendingRequest(value, index);

        if (this.server_state.currentIndex.get() == index) {
            if (!server_state.pendingRequests.offer(newRequest)) {
                // TODO: If this returns false, the queue is full. What should we do?
            }
            // Waking up the main loop since we have a new request to work on.
            this.server_state.main_loop.wakeup();
            // After learning the value, Paxos is finished. Reseting Paxos related state.
            this.server_state.finishPaxos();

            response = DadkvsPaxos.LearnReply.newBuilder().setLearnaccepted(true)
                    .setLearnindex(index).setLearnconfig(config).build();

        } else {
            // TODO: Index missmatch. This learn message is not related to our current paxos
            // instance.
            // Just answer with accepted = False?
            response = DadkvsPaxos.LearnReply.newBuilder().setLearnaccepted(false)
                    .setLearnindex(index).setLearnconfig(config).build();
        }
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}
