package dadkvs.server;

import java.util.ArrayList;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsMain;
import dadkvs.DadkvsMainServiceGrpc;
import dadkvs.DadkvsPaxos;
import dadkvs.util.CollectorStreamObserver;
import dadkvs.util.GenericResponseCollector;
import io.grpc.stub.StreamObserver;

public class DadkvsMainServiceImpl extends DadkvsMainServiceGrpc.DadkvsMainServiceImplBase {

    DadkvsServerState server_state;

    public DadkvsMainServiceImpl(DadkvsServerState state) {
        this.server_state = state;
    }

    @Override
    public void read(DadkvsMain.ReadRequest request,
            StreamObserver<DadkvsMain.ReadReply> responseObserver) {
        // for debug purposes
        System.out.println("Receiving read request:" + request);

        int reqid = request.getReqid();
        int key = request.getKey();
        VersionedValue vv = this.server_state.store.read(key);

        DadkvsMain.ReadReply response = DadkvsMain.ReadReply.newBuilder().setReqid(reqid)
                .setValue(vv.getValue()).setTimestamp(vv.getVersion()).build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void committx(DadkvsMain.CommitRequest request,
            StreamObserver<DadkvsMain.CommitReply> responseObserver) {
        // for debug purposes
        System.out.println("Receiving commit request:" + request);

        int reqid = request.getReqid();
        int key1 = request.getKey1();
        int version1 = request.getVersion1();
        int key2 = request.getKey2();
        int version2 = request.getVersion2();
        int writekey = request.getWritekey();
        int writeval = request.getWriteval();

        // for debug purposes
        System.out.println("reqid " + reqid + " key1 " + key1 + " v1 " + version1 + " k2 " + key2
                + " v2 " + version2 + " wk " + writekey + " writeval " + writeval);

        TransactionRecord txrecord =
                new TransactionRecord(key1, version1, key2, version2, writekey, writeval);
        PendingTransaction transaction = new PendingTransaction(txrecord, responseObserver);

        this.server_state.pendingTransactions.put(reqid, transaction);

        // Waking up the main loop since the received transaction might have the req id we decided
        // to process next trough consensus.
        this.server_state.main_loop.wakeup();

        if (this.server_state.i_am_leader) {
            while (!paxos(reqid)) {
                this.server_state.rnd.getAndAdd(this.server_state.n_servers);
            }
        }
    }

    private Boolean paxos(int reqid) {
        // for debug purposes
        System.out.println("Starting Paxos for reqid " + reqid);

        int config = this.server_state.store.read(0).getValue();

        // for debug purposes
        System.out.println("Starting Paxos Phase 1");
        DadkvsPaxos.PhaseOneRequest.Builder phase1_request =
                DadkvsPaxos.PhaseOneRequest.newBuilder();

        phase1_request.setPhase1Config(config);
        phase1_request.setPhase1Index(this.server_state.currentIndex.get());
        phase1_request.setPhase1Timestamp(this.server_state.rnd.get());

        ArrayList<DadkvsPaxos.PhaseOneReply> phase1_replies =
                new ArrayList<DadkvsPaxos.PhaseOneReply>();

        GenericResponseCollector<DadkvsPaxos.PhaseOneReply> phase1_collector =
                new GenericResponseCollector<DadkvsPaxos.PhaseOneReply>(phase1_replies,
                        this.server_state.n_servers);

        for (int i : this.server_state.configs[config]) {
            if (i == this.server_state.my_id)
                continue;

            CollectorStreamObserver<DadkvsPaxos.PhaseOneReply> phase1_observer =
                    new CollectorStreamObserver<DadkvsPaxos.PhaseOneReply>(phase1_collector);

            this.server_state.async_stubs[i].phaseone(phase1_request.build(), phase1_observer);
        }
        phase1_collector.waitForTarget(this.server_state.responses_needed);

        int agreedReqID = reqid;
        int acceptedRequests = 1;
        int maxRnd = 0;
        for (DadkvsPaxos.PhaseOneReply reply : phase1_replies) {
            if (reply.getPhase1Accepted()) {
                acceptedRequests++;
                int replyRnd = reply.getPhase1Timestamp();
                int replyVValue = reply.getPhase1Value();
                if (replyRnd > maxRnd && replyVValue != -1) {
                    agreedReqID = reply.getPhase1Value();
                    maxRnd = replyRnd;
                }
            }
        }
        if (acceptedRequests < this.server_state.responses_needed) {
            // Phase 1 failed, we couldn't get a majority
            return false;
        }

        // for debug purposes
        System.out.println("Startin Paxos Phase 2");

        // The leader is also an acceptor. Voting for the value we purposed.
        this.server_state.vval.set(agreedReqID);

        DadkvsPaxos.PhaseTwoRequest.Builder phase2_request =
                DadkvsPaxos.PhaseTwoRequest.newBuilder();

        phase2_request.setPhase2Config(config);
        phase2_request.setPhase2Index(this.server_state.currentIndex.get());
        phase2_request.setPhase2Value(agreedReqID);
        phase2_request.setPhase2Timestamp(this.server_state.rnd.get());

        ArrayList<DadkvsPaxos.PhaseTwoReply> phase2_replies =
                new ArrayList<DadkvsPaxos.PhaseTwoReply>();

        GenericResponseCollector<DadkvsPaxos.PhaseTwoReply> phase2_collector =
                new GenericResponseCollector<DadkvsPaxos.PhaseTwoReply>(phase2_replies,
                        this.server_state.n_servers);

        for (int i : this.server_state.configs[config]) {
            if (i == this.server_state.my_id)
                continue;

            CollectorStreamObserver<DadkvsPaxos.PhaseTwoReply> phase2_observer =
                    new CollectorStreamObserver<DadkvsPaxos.PhaseTwoReply>(phase2_collector);

            this.server_state.async_stubs[i].phasetwo(phase2_request.build(), phase2_observer);
        }

        // Paxos was successful. The next ReqId to be processed has been decided.
        return true;
    }
}
