package dadkvs.server;

import java.util.ArrayList;
import java.util.Iterator;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsMain;
import dadkvs.DadkvsMainServiceGrpc;
import dadkvs.DadkvsPaxos;
import dadkvs.util.CollectorStreamObserver;
import dadkvs.util.GenericResponseCollector;
import io.grpc.stub.StreamObserver;

public class DadkvsMainServiceImpl extends DadkvsMainServiceGrpc.DadkvsMainServiceImplBase {

    DadkvsServerState server_state;
    DadkvsPaxosServiceImpl paxos;
    int timestamp;

    public DadkvsMainServiceImpl(DadkvsServerState state) {
        this.server_state = state;
        this.timestamp = state.my_id;
    }

    @Override
    public void read(DadkvsMain.ReadRequest request,
            StreamObserver<DadkvsMain.ReadReply> responseObserver) {
        // for debug purposes
        System.out.println("Receiving read request:" + request);

        int reqid = request.getReqid();
        int key = request.getKey();
        VersionedValue vv = this.server_state.store.read(key);

        DadkvsMain.ReadReply response = DadkvsMain.ReadReply.newBuilder()
                .setReqid(reqid).setValue(vv.getValue()).setTimestamp(vv.getVersion()).build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void committx(DadkvsMain.CommitRequest request,
            StreamObserver<DadkvsMain.CommitReply> responseObserver) {
        // for debug purposes
        System.out.println("Receiving commit request:" + request);

        int reqid = request.getReqid();
        int key1 = request.getKey1();
        int version1 = request.getVersion1();
        int key2 = request.getKey2();
        int version2 = request.getVersion2();
        int writekey = request.getWritekey();
        int writeval = request.getWriteval();

        // for debug purposes
        System.out.println("reqid " + reqid + " key1 " + key1 + " v1 "
                + version1 + " k2 " + key2 + " v2 " + version2
                + " wk " + writekey + " writeval " + writeval);

        this.timestamp += this.server_state.n_servers;

        TransactionRecord txrecord = new TransactionRecord(key1, version1, key2,
                version2, writekey, writeval, this.timestamp);

        System.out.println("Paxos start");

        int config = this.server_state.store.read(0).getValue();
        int index = writekey; // IDK what should be here

        DadkvsPaxos.PhaseOneRequest.Builder phase_one_request = DadkvsPaxos.PhaseOneRequest.newBuilder();
        phase_one_request.setPhase1Config(config);
        phase_one_request.setPhase1Index(index);
        phase_one_request.setPhase1Timestamp(this.timestamp);

        ArrayList<DadkvsPaxos.PhaseOneReply> phase_one_responses = new ArrayList<DadkvsPaxos.PhaseOneReply>();
        GenericResponseCollector<DadkvsPaxos.PhaseOneReply> phase_one_collector = new GenericResponseCollector<DadkvsPaxos.PhaseOneReply>(
                phase_one_responses, this.server_state.n_servers);

        for (int i = 0; i < this.server_state.n_servers; i++) {
            if (i == this.server_state.my_id)
                continue;
            CollectorStreamObserver<DadkvsPaxos.PhaseOneReply> phase_one_observer = new CollectorStreamObserver<DadkvsPaxos.PhaseOneReply>(
                    phase_one_collector);
            this.server_state.async_stubs[i].phaseone(phase_one_request.build(), phase_one_observer);
        }
        phase_one_collector.waitForTarget(this.server_state.responses_needed);

        int acceptedValue = writeval;
        if (phase_one_responses.size() >= this.server_state.responses_needed) {
            Iterator<DadkvsPaxos.PhaseOneReply> phase_one_iterator = phase_one_responses.iterator();
            for (int i = 0; i < this.server_state.responses_needed; i++) {
                DadkvsPaxos.PhaseOneReply phase_one_reply = phase_one_iterator.next();
                if (phase_one_reply.getPhase1Accepted()) {
                    acceptedValue = phase_one_reply.getPhase1Value();
                    break;
                }
            }
        } else {
            System.out.println("Paxos phase one error");
            return;
        }

        DadkvsPaxos.PhaseTwoRequest.Builder phase_two_request = DadkvsPaxos.PhaseTwoRequest.newBuilder();
        phase_two_request.setPhase2Config(config);
        phase_two_request.setPhase2Index(index);
        phase_two_request.setPhase2Value(acceptedValue);
        phase_two_request.setPhase2Timestamp(this.timestamp);

        ArrayList<DadkvsPaxos.PhaseTwoReply> phase_two_responses = new ArrayList<DadkvsPaxos.PhaseTwoReply>();
        GenericResponseCollector<DadkvsPaxos.PhaseTwoReply> phase_two_collector = new GenericResponseCollector<DadkvsPaxos.PhaseTwoReply>(
                phase_two_responses, this.server_state.n_servers);

        for (int i = 0; i < this.server_state.n_servers; i++) {
            if (i == this.server_state.my_id)
                    continue;
            CollectorStreamObserver<DadkvsPaxos.PhaseTwoReply> phase_two_observer = new CollectorStreamObserver<DadkvsPaxos.PhaseTwoReply>(
                    phase_two_collector);
            this.server_state.async_stubs[i].phasetwo(phase_two_request.build(), phase_two_observer);
        }
        phase_two_collector.waitForTarget(this.server_state.responses_needed);

        boolean result = this.server_state.store.commit(txrecord);

        // for debug purposes
        System.out.println("Result is ready for request with reqid " + reqid);

        DadkvsMain.CommitReply response = DadkvsMain.CommitReply.newBuilder()
                .setReqid(reqid).setAck(result).build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}
