package dadkvs.server;

import java.util.ArrayList;
import java.util.Iterator;

/* these imported classes are generated by the hello-world-server contract */
import dadkvs.DadkvsMain;
import dadkvs.DadkvsPaxos;
import dadkvs.DadkvsPaxosServiceGrpc;

import dadkvs.util.GenericResponseCollector;
import dadkvs.util.CollectorStreamObserver;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;

public class MainLoop implements Runnable {
    DadkvsServerState server_state;

    private boolean has_work;

    public MainLoop(DadkvsServerState state) {
        this.server_state = state;
        this.has_work = false;
    }

    public void run() {
        while (true)
            this.doWork();
    }

    synchronized public void doWork() {
        System.out.println("Main loop do work start");
        this.has_work = false;
        while (this.has_work == false) {
            System.out.println("Main loop do work: waiting");
            try {
                wait();
            } catch (InterruptedException e) {
            }
        }

        PendingRequest pendingRequest = this.server_state.pendingRequests.peek();

        if (this.server_state.pendingTransactions.containsKey(pendingRequest.getReqid())) {

            PendingTransaction pendingTransaction =
                    this.server_state.pendingTransactions.get(pendingRequest.getReqid());

            boolean result = this.server_state.store.commit(pendingTransaction.getTransaction());

            // for debug purposes
            System.out
                    .println("Result is ready for request with reqid " + pendingRequest.getReqid());

            DadkvsMain.CommitReply response = DadkvsMain.CommitReply.newBuilder()
                    .setReqid(pendingRequest.getReqid()).setAck(result).build();

            StreamObserver<DadkvsMain.CommitReply> responseObserver =
                    pendingTransaction.getResponseObserver();

            responseObserver.onNext(response);
            responseObserver.onCompleted();

            // Removing the already processed reqid from the queue.
            this.server_state.pendingRequests.poll();
            // Removing the already processed transaction from the queue.
            this.server_state.pendingTransactions.remove(pendingRequest.getReqid());
        }
        System.out.println("Main loop do work finish");
    }

    synchronized public void wakeup() {
        this.has_work = true;
        notify();
    }
}
